name: CI/CD Lavabos FIB

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # PRIMER PAS: Comprovar que el codi és correcte (s'executa sempre)
  test-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Generate Prisma Client
        run: bun prisma generate

      - name: build check
        run: bun run build
        env:
          # Avis! Aquestes dades són fictícies (us ho juro) 
          DATABASE_URL: "postgresql://microones:mmmmmmmmmmmmmmmm@localhost:5432/lavabos-fib"
          NEXT_PUBLIC_API_URL: "http://localhost:3000"

# SEGON PAS: Desplegament real (NOMÉS si el primer pas és OK i estem a MAIN)
  deploy:
    needs: test-build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Connect to Tailscale
        uses: tailscale/github-action@v2
        with:
          authkey: ${{ secrets.TAILSCALE_AUTH_KEY }}

      - name: Executing remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # 1. Configurar l'entorn
            set -e
            export PATH=$PATH:/home/yerayzalaya/.bun/bin
            
            # 2. Entrar al directori
            cd /var/www/lavabos-fib
            
            # 3. Actualitzar codi i dependències
            git pull origin main
            bun install
            
            # 4. Base de dades
            bun prisma generate
            bun prisma migrate deploy
            
            # 5. Build del projecte Next.js
            bun run build
            
            # 6. Reiniciar l'aplicació amb PM2
            pm2 restart lavabos-fib || pm2 start "bun run start" --name "lavabos-fib"
